live_config_reload = true

[window]
decorations = 'Transparent'
padding = { x = 12, y = 16 }
opacity = 0.75

[font]
size = 14
normal = { family = 'Iosevka Nerd Font', style = 'Regular' }
bold = { family = 'Iosevka Nerd Font', style = 'Bold' }
italic = { family = 'Iosevka Nerd Font', style = 'Italic' }
bold_italic = { family = 'Iosevka Nerd Font', style = 'Bold Italic' }
offset = { x = 1, y = 0 }

[cursor]
style = { shape = 'Beam', blinking = 'On' }

[mouse]
hide_when_typing = true

[colors.primary]
background = '#282828'
foreground = '#ebdbb2'

[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'
